# Generated by Django 4.2.23 on 2025-09-06 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_hrtimeslot_hrinterviewbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRInterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_clarity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='How well the candidate addressed questions and communicated ideas')),
                ('technical_knowledge', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Demonstration of role-specific technical skills and knowledge')),
                ('communication_skills', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Ability to articulate thoughts clearly and professionally')),
                ('problem_solving', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Logical thinking and systematic approach to problems')),
                ('experience_examples', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Use of relevant examples and practical experience')),
                ('overall_score', models.FloatField(help_text='Average of all criteria scores')),
                ('strengths', models.JSONField(default=list, help_text='List of candidate strengths')),
                ('areas_for_improvement', models.JSONField(default=list, help_text='List of areas for improvement')),
                ('detailed_feedback', models.TextField(help_text='Comprehensive feedback explaining the evaluation')),
                ('recommendation', models.TextField(help_text='Brief recommendation for this candidate')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional HR notes or observations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='hr.hrinterviewbooking')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to='hr.hr')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateFeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(help_text="Candidate's reply to the feedback")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_replies', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hr.hrinterviewfeedback')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
