# Generated by Django 4.2.23 on 2025-09-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_hrinterviewfeedback_candidatefeedbackreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrinterviewbooking',
            name='actual_duration_minutes',
            field=models.IntegerField(default=0, help_text='Actual interview duration in minutes'),
        ),
        migrations.AddField(
            model_name='hrinterviewbooking',
            name='both_attended',
            field=models.BooleanField(default=False, help_text='Whether both HR and candidate attended'),
        ),
        migrations.AddField(
            model_name='hrinterviewbooking',
            name='candidate_joined_at',
            field=models.DateTimeField(blank=True, help_text='When candidate joined the meeting', null=True),
        ),
        migrations.AddField(
            model_name='hrinterviewbooking',
            name='candidate_left_at',
            field=models.DateTimeField(blank=True, help_text='When candidate left the meeting', null=True),
        ),
        migrations.AddField(
            model_name='hrinterviewbooking',
            name='hr_joined_at',
            field=models.DateTimeField(blank=True, help_text='When HR joined the meeting', null=True),
        ),
        migrations.AddField(
            model_name='hrinterviewbooking',
            name='hr_left_at',
            field=models.DateTimeField(blank=True, help_text='When HR left the meeting', null=True),
        ),
    ]
