# Generated by Django 4.2.23 on 2026-05-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_hrinterviewbooking_actual_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrinterviewbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Confirmation'), ('scheduled', 'Scheduled'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
    ]
