# Generated by Django 4.2.23 on 2026-05-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_hrinterviewbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrinterviewbooking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether the 10-minute reminder email has been sent'),
        ),
    ]
