# Generated by Django 4.2.23 on 2026-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_hrinterviewbooking_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrinterviewbooking',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('advanced', 'Advanced')], default='medium', max_length=20),
        ),
    ]
