# Generated by Django 4.2.23 on 2025-08-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidateprofile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='parsed_data',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
