# Generated by Django 4.2.23 on 2025-08-23 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0005_emailconfirmationotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('evaluations', models.JSONField(default=list)),
                ('average', models.FloatField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('answered_questions', models.IntegerField(default=0)),
                ('skipped_questions', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
