# Generated by Django 4.2.23 on 2026-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_interviewrecord_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
