# Generated by Django 4.2.23 on 2026-05-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_candidateprofile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecord',
            name='career_advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
