# Generated by Django 4.2.23 on 2026-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_interviewrecord_career_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecord',
            name='bio_angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewrecord',
            name='bio_disgusted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewrecord',
            name='bio_fearful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewrecord',
            name='bio_happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewrecord',
            name='bio_neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewrecord',
            name='bio_sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewrecord',
            name='bio_surprised',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewrecord',
            name='bio_total_frames',
            field=models.IntegerField(default=0),
        ),
    ]
